extends: 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  max-len:
    - error
    - 120
  new-cap:
    - error
    - capIsNewExceptions:
      - Q
  arrow-parens:
    - error
    - as-needed
